server:
  port: 8501

spring:
  application:
    name: microservice-advice-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
