server:
  port=8080

spring:
  application:
    name: advice-collection-microservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/advice_collection_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true